### ISSUE TITLE
midi-player-gh-pages demo question

### ISSUE THREAD

**Issue by yangyangnote** [rism-ch/midi-player#16]
1.I have moved the midi-player-gh-pages demo to local
2.There is also a wildwebmidi.data file in the folder
<img width="220" alt="屏幕快照 2020-03-24 下午2 57 09" src="https://user-images.githubusercontent.com/19338570/77397008-c779bc00-6ddf-11ea-834c-f09087f0a861.png">
3.When I put index.html in the browser, I can only display the player, but can't play it. What is the problem?
<img width="674" alt="屏幕快照 2020-03-24 下午2 59 13" src="https://user-images.githubusercontent.com/19338570/77397182-132c6580-6de0-11ea-8015-2a3a74cf8589.png">

**Comment by lpugin** [comment]
What's the console saying?

**Comment by yangyangnote** [comment]
I found the answer. For security reasons, or forbidding cross-domain access, Chrome does not support local Ajax access.
If you want to test, enter open -a "/ Applications / Google Chrome.app" --args --disable-web-security --user-data-dir = / Users / yourname / chromeDevUserData / 
and restart the browser
Thanks

**Comment by yangyangnote** [comment]
I found a solution to this problem
1. Add wildwebmidi to the folder, it must be at the same level as the html file to be displayed like
<img width="225" alt="屏幕快照 2020-03-27 上午9 59 17" src="https://user-images.githubusercontent.com/19338570/77713572-a8fb0700-7011-11ea-84ee-c43acd910dc9.png">
2. Reference https://github.com/rism-ch/midi-player/issues/16#issuecomment-604174350
