### ISSUE TITLE
Is this still the recommended player for MIDI with Verovio?

### ISSUE THREAD

**Issue by jericho-music** [rism-ch/midi-player#17]
I am trying to use this with Vue and needed to rebuild etc. Ran into some issues, but before digging deep wanted to check if this project is still considered 'alive' as there has not been any activity on this for a while.

I would like to be able to use just the player (without the UI) inside vue. So wanted to separate out Jquery and the UI design from it.

**Comment by lpugin** [comment]
The player is still being used. You can look at the develop-wasm branch for a more recent build.
