### ISSUE TITLE
Wonderful .. but no sound so far

### ISSUE THREAD

**Issue by rigaux** [rism-ch/midi-player#3]
Hi there,

Thanks a lot for the wonderful tool ! My problem: when I combine with Verovio/MEI, I do not get any sound. Example here:

http://neuma.huma-num.fr/home/opus/composers:brumel:Brumel_missa/

Seems that everything is OK. I suspect that I need some audio samples. Help will be much appreciated.

Philippe

**Comment by lpugin** [comment]
Did you also include the `wildwebmidi.data` file? I think it needs to be in the root directory of the site, which is quite unfortunate but I did not find another way to do it.

**Comment by rigaux** [comment]
Correct: we need the wildwebmidi.data file. This does appear in the instructions that just tells to include the .js and the .css in the template.

Unfortunately, wildwebmidi.data is search with respect to the current URL, which makes the solution a bit tricky when one uses a framework or pattern-based URLs. I found the solution for Django, in case someone is interested.

Thank you very very much for the great tool. It is wonderfully adapted to our needs.

Warmly

**Comment by lpugin** [comment]
Comment added here https://github.com/rism-ch/midi-player/commit/91ffd6a2d19ad725c539b4fe27167cfee886a68e
