### ISSUE TITLE
midi-player cutting off first and last notes

### ISSUE THREAD

**Issue by malcolmsailor** [rism-ch/midi-player#4]
Hello,

Great project! I'm hoping to use it.

However, I've noticed an issue: it seems that playback always begins *after* the first note. For instance, the Bach G minor invention that the demo page plays begins with a low G in the left-hand (you can see the score here: http://imslp.org/wiki/Invention_in_G_minor,_BWV_782_(Bach,_Johann_Sebastian)), but playback only begins after this note, with the right hand's sixteenth notes (at least on my computer).

Similarly, the end of midi files seems to be truncated. If the file ends with a long note, then it seems to be abruptly cut off (this is what seems to happen with the Bach invention). Sometimes, if a midi file ends with brief notes (rather than long notes), they seem to be cut off altogether.

I've reproduced the same behaviour in Chrome on my mac and my android phone, as well as in Safari.

I've been able to get around this issue by adding a dummy first and last note to all of my midi files, but this seems like a bit of a hack.

Malcolm

**Comment by lpugin** [comment]
It should be fixed
