### ISSUE TITLE
Method to read .mid file to use this player.

### ISSUE THREAD

**Issue by FullStackerWeb** [rism-ch/midi-player#8]
Hi @lpugin 

I am going to play the mid file to use this player.
I'd like you to let me know how can I import mid file to use your player asap.

Regards

**Comment by lpugin** [comment]
The MIDI file simply needs to be converted to a base64 encoded string. See this example:
https://github.com/rism-ch/midi-player/blob/gh-pages/example-song.js
You can do this in JavaScript with the window.btoa() function. See for example https://codepen.io/AshV/pen/pjodjV

**Comment by FullStackerWeb** [comment]
That works for me. I can play another midi file after converted to a base64 encoded string.
Thanks.

And I have one question.
I think It wasn't a high sound quality.
 
So I'd like you to explain how can I improve sound quality.
Best Regards.

**Comment by lpugin** [comment]
It is MIDI quality. If you want a better quality you will need to use a sound file format and with an audio player.

**Comment by FullStackerWeb** [comment]
Thanks for your support.
